### ISSUE TITLE
java.lang.IllegalArgumentException because of spark version string being blank

### ISSUE THREAD

**Issue by drnushooz** [MemVerge/splash#62]
I am testing Splash with Spark version 2.4.6 and Hadoop 2.8.5 for a use case. When I try to run tests in `SplashUnsafeSorterTest`, all of them fail with error message `Spark tried to parse '' as a Spark version string, but it could not find the major/minor/maintenance version numbers.` This issue doesn't happen with earlier versions of Spark. I have tested 2.4.0 and 2.4.1. The detailed stack trace in the output of `mvn test -Dspark.version=2.4.6` is below.
```
java.lang.ExceptionInInitializerError
	at org.apache.spark.SparkContext$$anonfun$3.apply(SparkContext.scala:183)
	at org.apache.spark.SparkContext$$anonfun$3.apply(SparkContext.scala:183)
	at org.apache.spark.internal.Logging$class.logInfo(Logging.scala:54)
	at org.apache.spark.SparkContext.logInfo(SparkContext.scala:73)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:183)
	at org.apache.spark.shuffle.TestUtil$.newSparkContext(TestUtil.scala:149)
	at org.apache.spark.shuffle.sort.SplashUnsafeSorterTest.newSparkContextWithForceSpillSize(SplashUnsafeSorterTest.scala:47)
	at org.apache.spark.shuffle.sort.SplashUnsafeSorterTest.testSpillLocalSortByKey(SplashUnsafeSorterTest.scala:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.IllegalArgumentException: Spark tried to parse '' as a Spark version string, but it could not find the major/minor/maintenance version numbers.
	at org.apache.spark.util.VersionUtils$.shortVersion(VersionUtils.scala:48)
	at org.apache.spark.package$.<init>(package.scala:94)
	at org.apache.spark.package$.<clinit>(package.scala)
	... 32 more

2020-09-03 15:19:03.664 WARN  [main] o.a.s.SparkContext : Another SparkContext is being constructed (or threw an exception in its constructor).  This may indicate an error, since only one SparkContext may be running in this JVM (see SPARK-2243). The other SparkContext was created at:
org.apache.spark.SparkContext.<init>(SparkContext.scala:76)
org.apache.spark.shuffle.TestUtil$.newSparkContext(TestUtil.scala:149)
org.apache.spark.shuffle.sort.SplashUnsafeSorterTest.newSparkContextWithForceSpillSize(SplashUnsafeSorterTest.scala:47)
org.apache.spark.shuffle.sort.SplashUnsafeSorterTest.testSpillLocalSortByKey(SplashUnsafeSorterTest.scala:73)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
org.testng.TestRunner.privateRun(TestRunner.java:648)
org.testng.TestRunner.run(TestRunner.java:505)
org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
org.testng.SuiteRunner.run(SuiteRunner.java:364)
```

**Comment by drnushooz** [comment]
I should have checked the `src/test/resources/spark-version-info.properties`. This contains a blank version entry causing this whole issue. The spark-core jar already contains this which gets loaded appropriately. Removing this file from test resources directory causes the tests to run without issues.
